Rozwiązania zadań z zajęć drugich

Zadanie 1
1. Napisz klasę Talia, która będzie zawierać inną klasę - klasę Karta, która spełnia następujące wymagania:
• rodzaj (Kier, Karo, Trefl, Pik)
• wartość (A,2,3,4,5,6,7,8,9,10,J,Q,K)
2. Dodaj metody:
• rozdaj, aby pobrać pojedynczą kartę z talii - karta po rozdaniu usuwana jest z talii
• przetasuj, która zapewnia że Talia składa się z 52 kart i ustawia je w sposób losowy

In [31]:
class Karta(object):
    """Karta do gry"""
    WARTOŚCI=["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"]
    RODZAJE=["Karo", "Kier", "Trefl", "Pik"]

    def __init__(self, wartość, rodzaj):
        self.wartość=wartość
        self.rodzaj=rodzaj
   
    def __str__(self):
        rep = self.wartość + self.rodzaj
        return rep
 
class Talia:
    """Talia kart do gry"""

    def __init__(self):
        self.karty=[]

    def __str__(self):
        if self.karty:
            rep = ""
            for karta in self.karty:
                rep+=str(karta)+ "  "
        else:
            rep = "<pusta>"
        return rep
       
    def clear(self):
        self.karty=[]

    def add(self, karta):
        self.karty.append(karta)

    def rozdajwszystkie(self):
        for rodzaj in Karta.RODZAJE:
            for wartość in Karta.WARTOŚCI:
                self.add(Karta(wartość, rodzaj))
   
    def przetasuj(self):
        import random
        licznik=0
        for liczba in self.karty:
            licznik+=1
        if licznik==52:
            print("Ilość kart w talii:", licznik)
        elif licznik < 52:
            self.clear()
            self.rozdajwszystkie()
            licznik2=0
            for liczba2 in self.karty:
                licznik2+=1        
            print("Ilość kart w talii:", licznik2)
        random.shuffle(self.karty)

    def rozdaj(self):
        import random
        karta=random.choice(self.karty)
        self.karty.remove(karta)
        print(karta)


Talia1 = Talia()
Talia1.rozdajwszystkie()
print("\nUtworzyłem nową talię.")
print("Talia:")
print(Talia1)
print("\nPrzetasowałem talię.")
Talia1.przetasuj()
print(Talia1)
print("\nLosowa karta:")
Talia1.rozdaj()
print("\nPrzetasowałem talię.")
Talia1.przetasuj()
print(Talia1)


Utworzyłem nową talię.
Talia:
AKaro  2Karo  3Karo  4Karo  5Karo  6Karo  7Karo  8Karo  9Karo  10Karo  JKaro  QKaro  KKaro  AKier  2Kier  3Kier  4Kier  5Kier  6Kier  7Kier  8Kier  9Kier  10Kier  JKier  QKier  KKier  ATrefl  2Trefl  3Trefl  4Trefl  5Trefl  6Trefl  7Trefl  8Trefl  9Trefl  10Trefl  JTrefl  QTrefl  KTrefl  APik  2Pik  3Pik  4Pik  5Pik  6Pik  7Pik  8Pik  9Pik  10Pik  JPik  QPik  KPik  

Przetasowałem talię.
Ilość kart w talii: 52
JKaro  QKaro  8Trefl  4Pik  AKaro  8Pik  APik  2Kier  4Karo  QTrefl  JTrefl  8Karo  7Kier  5Karo  10Karo  9Karo  5Kier  3Trefl  KTrefl  9Kier  3Karo  JPik  5Pik  10Pik  9Trefl  JKier  10Kier  KKaro  7Trefl  3Pik  ATrefl  3Kier  7Karo  5Trefl  6Karo  2Pik  10Trefl  6Kier  AKier  6Trefl  6Pik  9Pik  2Trefl  KKier  2Karo  QKier  8Kier  KPik  7Pik  QPik  4Trefl  4Kier  

Losowa karta:
7Trefl

Przetasowałem talię.
Ilość kart w talii: 52
5Karo  10Pik  8Kier  9Pik  QPik  9Trefl  8Trefl  JPik  5Trefl  7Kier  7Pik  JKaro  6Pik  5Pik  QTrefl  3Trefl  9Karo  1

Zadanie 2
1. Napisz klasę Pojazd, która spełnia następujące wymagania:
• zawiera pole predkosc max
• zawiera pole mileage (ilośc kilometrów, do przejechania na jednym litrze)
• wyświetla: (240, 18)

In [1]:
class Pojazd:
    def __init__(self, predkosc_max, mileage):
        self.predkosc_max = predkosc_max
        self.mileage= mileage
        
    def __str__(self):
        return '({}, {})'.format(self.predkosc_max, self.mileage)   

        
mojPojazd =Pojazd(240, 18)
print (mojPojazd)

(240, 18)


2. Napisz klasę pochodną Bus, która:
• zawiera pole nazwa
• zawiera pole predkosc max
• zawiera pole mileage (ilośc kilometrów, do przejechania na jednym litrze)
• wyświetla: (”School Volvo”, 180, 12)

In [38]:
class Pojazd:
    def __init__(self, predkosc_max, mileage):
        self.predkosc_max = predkosc_max
        self.mileage= mileage
        
    def __str__(self):
        return '({}, {})'.format(self.predkosc_max, self.mileage)   

class Bus(Pojazd):
    def __init__(self, nazwa, predkosc_max, mileage):
        super().__init__(predkosc_max, mileage)
        self.nazwa = nazwa
    def wyswietl(self):
        print((self.nazwa, self.predkosc_max, self.mileage))
    def __str__(self):
        return '({}, {}, {})'.format(self.nazwa, self.predkosc_max, self.mileage)  
    
mojBus =Bus("School Volvo", 180, 12)
print (mojBus)

(School Volvo, 180, 12)


3. Rozszerz Klasę Bus tak, aby rozszerzyło argumenty o pojemnosc calkowita z wartością domyślną 50

In [41]:
class Pojazd:
    def __init__(self, predkosc_max, mileage):
        self.predkosc_max = predkosc_max
        self.mileage= mileage
        
    def __str__(self):
        return '({}, {})'.format(self.predkosc_max, self.mileage)   

class Bus(Pojazd):
    def __init__(self, nazwa, predkosc_max, mileage, pojemnosc=50):
        super().__init__(predkosc_max, mileage)
        self.nazwa = nazwa
        self.pojemnosc = pojemnosc
    def __str__(self):
        return '({}, {}, {}, {})'.format(self.nazwa, self.predkosc_max, self.mileage, self.pojemnosc)  
    
mojBus =Bus("School Volvo", 180, 12)
print (mojBus)

(School Volvo, 180, 12, 50)


4. Napisz klasę Samochod, która odziedziczy całość parametrów (po klasie Pojazd)

In [42]:
class Pojazd:
    def __init__(self, predkosc_max, mileage):
        self.predkosc_max = predkosc_max
        self.mileage= mileage
        
    def __str__(self):
        return '({}, {})'.format(self.predkosc_max, self.mileage)  

class Samochod(Pojazd):
    def __init__(self, predkosc_max, mileage):
        super().__init__(predkosc_max, mileage)

mojPojazd =Pojazd(240, 18)
print (mojPojazd)
mojSamochod =Samochod(240, 18)
print (mojSamochod)

(240, 18)
(240, 18)


5. W klasie Pojazd dodaj atrybut klasowykolor o wartości domyślnej biały, który ma być odziedziczony przez klasy Bus i
Samochod. Dopisz (”Audi Q5”, 240. 18) oraz (”School Volvo”, 180, 12)

In [53]:
class Pojazd:
    kolor = "biały"
    def __init__(self, predkosc_max, mileage):
        self.predkosc_max = predkosc_max
        self.mileage= mileage
        
    def __str__(self):
        return '({}, {})'.format(self.predkosc_max, self.mileage)  

class Samochod(Pojazd):
    def __init__(self, predkosc_max, mileage):
        super().__init__(predkosc_max, mileage)

class Bus(Pojazd):
    def __init__(self, nazwa, predkosc_max, mileage):
        super().__init__(predkosc_max, mileage)
        self.nazwa = nazwa
    def __str__(self):
        return '({}, {}, {})'.format(self.nazwa, self.predkosc_max, self.mileage)  
    
mojBus =Bus("School Volvo", 180, 12)
print (mojBus)
print(mojBus.kolor)
mojBus2 =Bus("Audi Q5", 240, 80)
print (mojBus2)


(School Volvo, 180, 12)
biały
(Audi Q5, 240, 80)


6. Rozszerz klasę Pojazd w następujący sposób:
• dodaj atrybut Opłata, który obliczysz mnożąc liczbę miejsc o 100, a jeśli pojazd jest w klasie Bus, to dodajesz jeszcze
10 procent opłaty


In [63]:
class Pojazd:
    def __init__(self, predkosc_max, mileage, liczba_miejsc):
        self.predkosc_max = predkosc_max
        self.mileage = mileage
        self.liczba_miejsc = liczba_miejsc
        self.opłata = self.liczba_miejsc * 100

        if isinstance(self, Bus):
            self.opłata *= 1.1

class Bus(Pojazd):
    def __init__(self, nazwa, predkosc_max, mileage, liczba_miejsc):
        super().__init__(predkosc_max, mileage, liczba_miejsc)
        self.nazwa = nazwa
        self.liczba_miejsc=liczba_miejsc
    def __str__(self):
        return '({}, {}, {})'.format(self.nazwa, self.predkosc_max, self.mileage) 


mojBus =Bus("School Volvo", 180, 12, 20)
print (mojBus)
opłata = mojBus.opłata
print(opłata)

(School Volvo, 180, 12)
2200.0
